### ISSUE TITLE
About setting the performance level of AMD Instinct MI100 by rocm-smi

### ISSUE THREAD

**Issue by xwentian2020** [ROCm/rocm_smi_lib#101]
Hi,
According to the information promoted by running rocm-smi -h on AMD Instinct MI100 GPU, it can be preset by the rocm-smi command to a specific condition, e.g., its performance level in working can be set by rocm-smi --setperflevel [low| high | auto | manual]. 

Here I have a few questions about the use of the rocm-smi command with its --setperflevel flag. 
1. What is the difference in performance between those parameters of this flag, like auto, high, low, manual?
2. Is there any other parameters available for this flag?
3. When this flag is set by "manual", anything else should be done to get MI100 into its best status for a specific computing task?

I am now doing some benchmarking tests on MI100 for its maximum performance in some HPC work, and consider the rocm-smi command is a tool for the intention to get reliable performance on this GPU device. 

Thanks for any suggestions on the use of the AMD GPUs.

**Comment by ppanchad-amd** [comment]
@xwentian2020 Apologies for the lack of response. Do you still need assistance with this ticket? Thanks!

**Comment by harkgill-amd** [comment]
Hi @xwentian2020, 
1. The difference between each of the parameters is as follows
    - auto: Automatically change values based on GPU workload
    - low: Keep values low, regardless of workload
    - high: Keep values high, regardless of workload
    - manual: Only use values defined by –setsclk and –setmclk
2. There are no other parameters for the `--setperflevel` flag.
3. After setting the flag to manual, you can note the available frequencies with `rocm-smi -s`. From there, you can set the frequency to any of the available frequencies with `rocm-smi --setclk`

For more information on the different flags, please see the [Detailed Option Descriptions](https://rocm.docs.amd.com/projects/rocm_smi_lib/en/latest/how-to/use-python.html#detailed-option-descriptions) section in the ROCm SMI LIB documentation. If you have any follow-up questions, please leave a comment and I will re-open this ticket. Thanks!
