### ISSUE TITLE
driverInitialized check not valid

### ISSUE THREAD

**Issue by mrusme** [ROCm/rocm_smi_lib#102]
[This](https://github.com/RadeonOpenCompute/rocm_smi_lib/blob/66e101a0ffb49df3c34f14e8669856381ce8d23d/python_smi_tools/rocm_smi.py#L69) check is not valid since one can have the GPU module baked into the kernel. In that case, `lsmod`/`/proc/modules` won't report it.

**Comment by littlewu2508** [comment]
https://github.com/RadeonOpenCompute/rocminfo/issues/42#issuecomment-870846291 may help

**Comment by dmitrii-galantsev** [comment]
Fixed as of 9f6614e83b6d5a09015efb76ed1421605be612dd. Please reopen if you disagree :)

**Comment by LtdJorge** [comment]
Hi @dmitrii-galantsev could you check #189 out? It's based on @littlewu2508's #104 and simplifies the code a bit by not spawning a shell, as @keryell mentioned in that PR.

I patched my rocm-smi with this:
![image](https://github.com/user-attachments/assets/158753f5-31c2-4bbf-a7d0-bcadc05ccf6f)
(Ignore the weird path, just Gentoo things)

It works correctly:
![image](https://github.com/user-attachments/assets/ee7cd419-8cb7-4a03-a165-e5b352499802)

My AMDGPU is built-in:
![image](https://github.com/user-attachments/assets/b2b65a22-8e3a-43e2-9eb3-39868873f35c)

**Comment by taylding-amd** [comment]
Thank you very much for the PR, @LtdJorge! I will go ahead and close the issue, as the PR will resolve it and will be merged through AMD's internal system.
