### ISSUE TITLE
rocm-smi --setfan 100% temporarily increases GPU speeds, but they shortly revert

### ISSUE THREAD

**Issue by githubbic** [ROCm/rocm_smi_lib#115]
I have four GPUs in this machine: All are navi cards. A 5500XT, despite rocm-smi saying it succeeds, does not increase its fan speed at all.
The other GPUs will, after the machine becomes unresponsive to all inputs for a few moments, ramp up to 100%, but then come back down almost immediately.

**Comment by rakataprime** [comment]
I have similar issues with other rocm-smi on Radeon VII with rocm version 5.4.1 with kernel  5.15.0-58-generic  on  Ubuntu 20.04.1. 
settings i have tried include powercap, clock speeds, and voltages.  Eventually the gpu resets and wipes out the stored settings during use.  I have had issues with the following cmds:
`rocm-smi --setperflevel manual 
rocm-smi --setvc 2 1701 915 --autorespond y
rocm-smi --setsrange 808 1740 --autorespond y`

**Comment by ppanchad-amd** [comment]
@githubbic @rakataprime Apologies for the lack of response. Please check if your issue still occurs with the latest ROCm 6.2. If not, please close the ticket. Thanks!

**Comment by ppanchad-amd** [comment]
@githubbic Closing ticket due to lack of activity. Please feel free to re-open ticket if you still encounter the issue with the latest ROCm. Thanks!
