### ISSUE TITLE
rsmitst64 and rocm-smi -a fail on OD_VDDC_CURVE with ppfeaturemask set

### ISSUE THREAD

**Issue by antimatterizer** [ROCm/rocm_smi_lib#116]
Hello!

Recently back into ROCm and working on getting SMI going on 6900xt with Ubuntu 22.04, kernel 5.17.0-1025-oem and ROCm 5.4.1.  All functionality works in SMI save for anything requiring the featuremask.  With it set, I receive the error below:

/home/mk/Installs/rocm_smi_lib/src/rocm_smi.cc:1158: rsmi_status_t get_od_clk_volt_info(uint32_t, rsmi_od_volt_freq_data_t*): Assertion `val_vec[kOD_VDDC_CURVE_label_array_index] == "OD_VDDC_CURVE:"' failed.
Aborted

Thanks!

**Comment by antimatterizer** [comment]
Without featuremask set, response is: 

GPU[0]		: Not supported on the given system
GPU[1]		: Not supported on the given system

**Comment by rakataprime** [comment]
did u set performance to manual like 
`rocm-smi --setperflevel manual `
` rocm-smi --setvc 2 1701 915 --autorespond y`
` rocm-smi --setsrange 808 1740 --autorespond y`

**Comment by ppanchad-amd** [comment]
@antimatterizer Apologies for the lack of response.  Did you try @rakataprime suggestions above? If you no longer require assistance with your issue, please close the ticket. Thanks!

**Comment by ppanchad-amd** [comment]
@antimatterizer Closing ticket due to lack of activity.  Please feel free to re-open ticket if you still encounter the issue with the latest ROCm. Thanks!
