### ISSUE TITLE
Does it support Arm64?

### ISSUE THREAD

**Issue by hailin84** [ROCm/rocm_smi_lib#59]
Our servers use arm64 cpus. Hope it can support as well.

**Comment by KnifeeOneOne** [comment]
Our servers use arm64 cpus. Hope it can support as well. +1

**Comment by dmitrii-galantsev** [comment]
Hm. I don't have a machine to try this on.
Officially we do not package anything for non-x86 systems afaik.
If anyone has one they can share via SSH - I'll gladly poke around :).

**Comment by cgmb** [comment]
Debian has built much of the ROCm stack for arm64, including rocm-smi. I'm told that on some arm64 systems, the Debian ROCm packages do more or less function correctly. I imagine that likely holds true for rocm-smi, but I don't have a system to test it with, either.
