### ISSUE TITLE
exception reading frequencies on Renoir APU 4650G

### ISSUE THREAD

**Issue by yodor** [ROCm/rocm_smi_lib#81]
$ /opt/rocm/bin/rocm-smi -d 1 --showall

======================= ROCm System Management Interface =======================
========================= Version of System Component ==========================
Driver version: 5.11.10-gentoo
================================================================================
====================================== ID ======================================
GPU[1]          : GPU ID: 0x1636
================================================================================
================================== Unique ID ===================================
GPU[1]          : Unique ID: N/A
================================================================================
==================================== VBIOS =====================================
GPU[1]          : VBIOS version: 113-RENOIR-033
================================================================================
================================= Temperature ==================================
GPU[1]          : Temperature (Sensor edge) (C): 28.0
GPU[1]          : Temperature (Sensor junction) (C): N/A
GPU[1]          : Temperature (Sensor memory) (C): N/A
================================================================================
========================== Current clock frequencies ===========================
Exception caught: map::at
ERROR: GPU[1]           : dcefclk clock is unsupported
python3: /storage/work/local/rocm_smi_lib/src/rocm_smi.cc:894: rsmi_status_t get_frequencies(amd::smi::DevInfoTypes, uint32_t, rsmi_frequencies_t*, uint32_t*): Assertion `f->frequency[i-1] <= f->frequency[i]' failed.
Aborted (core dumped)

**Comment by dmitrii-galantsev** [comment]
this is no longer asserted
