### ISSUE TITLE
Update the default soname for tarballs

### ISSUE THREAD

**Issue by haampie** [ROCm/rocm_smi_lib#83]
When building rocm_smi_lib from a source tarball the soname defaults to 1.0.0

Can you please update the soname in the cmake script upon releases so that the soname always makes sense?

**Comment by charis-poag-amd** [comment]
This will be fixed in rocm 6.0 - see our latest cmake builds. You should see package names are already updated in master branch.

**Comment by dmitrii-galantsev** [comment]
develop branch*.
And no. It won't be fixed in 6.0.
I have a change pending internally that I will probably push out sometime soon. But I'm unsure..
Maybe 6.1?

Related: [This patch](https://salsa.debian.org/rocm-team/rocm-smi-lib/-/blob/master/debian/patches/0007-rocm_smi64-soversion.patch) from debian sets the SO version to 1.0.0. My change that I haven't published yet would use the global version number from here https://github.com/ROCm/rocm_smi_lib/blob/c6b0c93e6fd34851c342a3c47921ec9b9e6f336f/CMakeLists.txt#L38

Is that a valid behavior to set the SO and tar to 7.0?

@emollier @haampie Do y'all have any comments?

```diff
From 7dcc89b133953f3e671654fdd4dc754c750b2946 Mon Sep 17 00:00:00 2001
From: Galantsev, Dmitrii <dmitrii.galantsev@amd.com>
Date: Thu, 30 Nov 2023 15:39:57 -0600
Subject: [PATCH] Fix SOVERSION if building without release tags

Change-Id: Idb3e2b16bb94e2950bd31932089e0e9b2193e2ca
Signed-off-by: Galantsev, Dmitrii <dmitrii.galantsev@amd.com>
---

diff --git a/rocm_smi/CMakeLists.txt b/rocm_smi/CMakeLists.txt
index 645e598..52d3e15 100755
--- a/rocm_smi/CMakeLists.txt
+++ b/rocm_smi/CMakeLists.txt
@@ -39,7 +39,8 @@
 
 # Debian package specific variables
 # Set a default value for the package version
-get_version_from_tag("1.0.0.0" ${SO_VERSION_GIT_TAG_PREFIX} GIT)
+# Use package version for convenience. At the time of writing both are 7.0.0
+get_version_from_tag("${CPACK_PACKAGE_VERSION_MAJOR}.${CPACK_PACKAGE_VERSION_MINOR}.0.0" ${SO_VERSION_GIT_TAG_PREFIX} GIT)
 
 # VERSION_* variables should be set by get_version_from_tag
 if ( ${ROCM_PATCH_VERSION} )
```

**Comment by emollier** [comment]
Hi Dmitrii,

The Debian patch you mention stemmed from the apparent impression that the soversion bump somewhere between 5.2 and 5.7 was not called for: there did not seem to be any ABI breakage that looked to justify the bump from 1, let alone up to 5 at once, at the time of the Debian patch.  From [Debian wiki's Upstream Guide]:

> Assign a SONAME, track ABI compatibility and change the SONAME when ABI compatibility is broken.

[Debian wiki's Upstream Guide]: https://wiki.debian.org/UpstreamGuide#Libraries

The [Debian policy manual section on Libraries] is also worth further reading, although more oriented towards Debian packagers.

[Debian policy manual section on Libraries]: https://www.debian.org/doc/debian-policy/ch-sharedlibs.html

In addition, but this is a Debian specific issue, the bump to soversion 5 would have required manual intervention from the Debian package archive team to remove the librocm-smi64-1 package in favor of librocm-smi64-5 (involving potentially a volunteer-time-consuming full review of the source code), then a scheduling a transition slot with the Debian release team to schedule a reconstruction of all reverse dependencies so they link to the new revision of the library.

All that being said, I'm not comfortable having a delta between librocm-smi64.so.1 from Debian's ROCm 5.7 distribution, and librocm-smi64.so.5 from upstream's ROCm 5.7, and this would effectively make reverse dependent binaries incompatible between the two distributions.  Besides, there is also the risk that I was wrong with such a patch (e.g. if I missed a sequence of breaking changes between 5.2 and 5.7), in which case it is a good thing that the new revision of the package with the patch hasn't made it to the Debian archive yet.  ;)

In hope this clarifies things,
Étienne.

**Comment by dmitrii-galantsev** [comment]
@emollier Thanks for the extra info! I definitely want to make the maintainer's jobs easier :)
I have some reading to do...

Frankly I don't know that much about packaging. I'm just the only one willing to touch CMake and break things.

**Comment by dmitrii-galantsev** [comment]
We're sticking with the 7.2.0 and so on. If this is still a problem - please reopen this issue or open a new one.
