### ISSUE TITLE
Can you create a flat directory structure on install?

### ISSUE THREAD

**Issue by haampie** [ROCm/rocm_smi_lib#84]
Currently;

```
./
├── lib
│   ├── librocm_smi64.so -> ../rocm_smi/lib/librocm_smi64.so
│   └── librocm_smi64.so.1 -> ../rocm_smi/lib/librocm_smi64.so.1
├── oam
│   ├── include
│   │   └── oam
│   │       ├── amd_oam.h
│   │       └── oam_mapi.h
│   └── lib
└── rocm_smi
    ├── docs
    │   ├── README.md
    │   └── ROCm_SMI_Manual.pdf
    │       └── refman.pdf
    ├── include
    │   └── rocm_smi
    │       ├── kfd_ioctl.h
    │       └── rocm_smi.h
    └── lib
        ├── librocm_smi64.so -> librocm_smi64.so.1
        ├── librocm_smi64.so.1 -> librocm_smi64.so.1.0
        └── librocm_smi64.so.1.0
```

Can you just make it flat?

```
./
├── lib
│   ├── librocm_smi64.so -> librocm_smi64.so.1
│   ├── librocm_smi64.so.1 -> librocm_smi64.so.1.0
│   ├── librocm_smi64.so.1.0
│   ├── liboam.so -> liboam.so.1
│   ├── liboam.so.1 -> liboam.so.1.0
│   └── liboam.so.1.0
├── include
│   ├── rocm_smi
│   │   ├── kfd_ioctl.h
│   │   └── rocm_smi.h
│   └── oam
│       ├── amd_oam.h
│       └── oam_mapi.h
└── docs
    ├── README.md
    └── ROCm_SMI_Manual.pdf
        └── refman.pdf

**Comment by musicinmybrain** [comment]
Oh, this would be great. I keep wanting to package `rocm_smi_lib` for Fedora Linux, and this is exactly what I would have to do manually. It would be great if the install were “normal” to begin with, and I didn’t have to try to rearrange it without accidentally breaking anything.

**Comment by Mystro256** [comment]
I think it would be best to follow the FHS and do:

├── lib
│   ├── librocm_smi64.so -> librocm_smi64.so.1
│   ├── librocm_smi64.so.1 -> librocm_smi64.so.1.0
│   ├── librocm_smi64.so.1.0
│   ├── liboam.so -> liboam.so.1
│   ├── liboam.so.1 -> liboam.so.1.0
│   └── liboam.so.1.0
├── include
│   ├── rocm_smi
│   │   ├── kfd_ioctl.h
│   │   └── rocm_smi.h
│   └── oam
│       ├── amd_oam.h
│       └── oam_mapi.h
└── share
    └── rocm_smi (or oam where applicable)
        ├── README.md
        ├── ROCm_SMI_Manual.pdf
        └── refman.pdf

CMake also has a library for this:
https://cmake.org/cmake/help/latest/module/GNUInstallDirs.html

Where you include(GNUInstallDirs), then replace "lib" with ${CMAKE_INSTALL_LIBDIR}, replace "include" with ${CMAKE_INSTALL_INCLUDEDIR}, and replace "share" with ${CMAKE_INSTALL_DATADIR}.
This allows distros or users to customise how they want to install these files. Thunk already does this, which is fantastic in my eyes.

**Comment by t-tye** [comment]
[AMD Official Use Only]

Under share we need something like:

Share -->doc --><component>-->*.[pdf,md,txt]
      -->html--><component>-->*.html
      -->info--><component>-->*.info
      -->man -->man1-->*.1
             -->man5-->*.5
      --><component>-->*

Thanks,
-Tony

**Comment by Maxzor** [comment]
> I think it would be best to follow the FHS and do:
>... 
> CMake also has a library for this: https://cmake.org/cmake/help/latest/module/GNUInstallDirs.html
> 
> Where you include(GNUInstallDirs), then replace "lib" with ${CMAKE_INSTALL_LIBDIR}, replace "include" with ${CMAKE_INSTALL_INCLUDEDIR}, and replace "share" with ${CMAKE_INSTALL_DATADIR}. This allows distros or users to customise how they want to install these files. Thunk already does this, which is fantastic in my eyes.

Totally!

**Comment by dmitrii-galantsev** [comment]
We do this now! :)
Thank you for pushing for this. The previous design was ridiculous.
In fact all rocm things should follow a sane flat structure now.
