### ISSUE TITLE
Unable to get full info dump from -a

### ISSUE THREAD

**Issue by Velkas** [ROCm/rocm_smi_lib#86]
```
======================= ROCm System Management Interface =======================
========================= Version of System Component ==========================
Driver version: 5.10.0-7-amd64
================================================================================
====================================== ID ======================================
GPU[0]		: GPU ID: 0x687f
================================================================================
================================== Unique ID ===================================
GPU[0]		: Unique ID: 0x213fab3ebd840c4
================================================================================
==================================== VBIOS =====================================
GPU[0]		: VBIOS version: 113-D0500100-102
================================================================================
================================= Temperature ==================================
GPU[0]		: Temperature (Sensor edge) (C): 59.0
GPU[0]		: Temperature (Sensor junction) (C): 59.0
GPU[0]		: Temperature (Sensor memory) (C): 60.0
================================================================================
========================== Current clock frequencies ===========================
GPU[0]		: dcefclk clock level: 0: (600Mhz)
ERROR: GPU[0] 		: fclk clock is unsupported
GPU[0]		: mclk clock level: 3: (945Mhz)
GPU[0]		: sclk clock level: 0: (852Mhz)
GPU[0]		: socclk clock level: 5: (960Mhz)
python3: /home/<username>/Downloads/rocm_smi_lib-rocm-4.1.0/src/rocm_smi.cc:898: rsmi_status_t get_frequencies(amd::smi::DevInfoTypes, uint32_t, rsmi_frequencies_t*, uint32_t*): Assertion `f->current == RSMI_MAX_NUM_FREQUENCIES + 1' failed.
Aborted
```

Having issues just getting the info from all this. Not sure what all I need to provide for help.

Card: Vega64
OS: SparkyLinux 6 (Po-Tolo) [Debian testing] with 5.10.0-7-amd64 drivers.

I can do some manual control stuff like setting fans, but things like setting memclock say successful then don't actually change.

**Comment by HoorayJorge** [comment]
Having a similar issue.  Ubuntu 20.04.3, amdspu-pro 20.30, 6600XT
`======================= ROCm System Management Interface =======================
========================= Supported clock frequencies ==========================
GPU[0]		: Supported dcefclk frequencies on GPU0
GPU[0]		: 0: 417Mhz
GPU[0]		: 1: 480Mhz *
GPU[0]		: 2: 1200Mhz
GPU[0]		: 
GPU[0]		: Supported fclk frequencies on GPU0
GPU[0]		: 0: 500Mhz
GPU[0]		: 1: 1248Mhz *
GPU[0]		: 2: 1801Mhz
GPU[0]		: 
GPU[0]		: Supported mclk frequencies on GPU0
GPU[0]		: 0: 96Mhz *
GPU[0]		: 1: 541Mhz
GPU[0]		: 2: 675Mhz
GPU[0]		: 3: 1000Mhz
GPU[0]		: 
python3: /home/farmer/rocm_smi_lib/src/rocm_smi.cc:913: rsmi_status_t get_frequencies(amd::smi::DevInfoTypes, uint32_t, rsmi_frequencies_t*, uint32_t*): Assertion `f->frequency[i-1] <= f->frequency[i]' failed.`

**Comment by ppanchad-amd** [comment]
@Velkas Apologies for the lack of response. Vega64 is no longer supported as of the latest ROCm 6.2. Closing ticket. Thanks!
