### ISSUE TITLE
Debian roc-smi manpage for review

### ISSUE THREAD

**Issue by Maxzor** [ROCm/rocm_smi_lib#92]
Dear rocm-smi-lib maitainers,
Please review and suggest any correction before upload [on this manpage](https://salsa.debian.org/rocm-team/rocm-smi-lib/-/blob/master/debian/roc-smi.1).
It is a merge of the output of roc-smi --help and the README.md .

In particular if you would like any personal author to be cited.

If you find it welcome, in order to streamline future updates, I can submit a comprehensive PR on the README that would help a lot the production of future man pages here.

**Comment by kentrussell** [comment]
We have a bit of a change coming up regarding some of the wording in the disclaimer (see https://github.com/RadeonOpenCompute/rocm_smi_lib/issues/97) and I'd rather that be incorporated into any man page, but I definitely have no issue with the work you've done there. If you want to submit the PR here, we can review here and then merge it internally and get it aligned with the work you guys are doing over there. Thanks!

**Comment by ppanchad-amd** [comment]
@Maxzor Can we close this ticket? Thanks!
